"""incidents, events, proposals, executions, jobs, kb

Revision ID: 18fb2dd99f4c
Revises: 3decffad9bc8
Create Date: 2026-09-02 23:59:49.604302
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "18fb2dd99f4c"
down_revision: str | None = "3decffad9bc8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "control_plane_state",
        sa.Column("scenario_key", sa.String(length=128), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("scenario_key", name=op.f("pk_control_plane_state")),
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("scenario_key", sa.String(length=128), nullable=False),
        sa.Column("service", sa.String(length=128), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=True),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "investigating",
                "awaiting_approval",
                "remediating",
                "verifying",
                "resolved",
                "needs_attention",
                "closed",
                name="incident_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("slack_channel_id", sa.String(length=32), nullable=True),
        sa.Column("slack_thread_ts", sa.String(length=32), nullable=True),
        sa.Column(
            "opened_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('SEV1','SEV2','SEV3')", name=op.f("ck_incidents_severity_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_index(op.f("ix_incidents_key"), "incidents", ["key"], unique=True)
    op.create_index(op.f("ix_incidents_scenario_key"), "incidents", ["scenario_key"], unique=False)
    op.create_index(
        "ix_incidents_slack_thread",
        "incidents",
        ["slack_channel_id", "slack_thread_ts"],
        unique=False,
    )
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_table(
        "kb_chunks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("chunk_id", sa.String(length=128), nullable=False),
        sa.Column("corpus", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("corpus IN ('kb','history')", name=op.f("ck_kb_chunks_corpus_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kb_chunks")),
    )
    op.create_index(op.f("ix_kb_chunks_chunk_id"), "kb_chunks", ["chunk_id"], unique=True)
    op.create_index(op.f("ix_kb_chunks_corpus"), "kb_chunks", ["corpus"], unique=False)
    op.create_table(
        "slack_deliveries",
        sa.Column("delivery_key", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "received_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("delivery_key", name=op.f("pk_slack_deliveries")),
    )
    op.create_table(
        "incident_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "created",
                "investigation_started",
                "evidence_gathered",
                "proposal_created",
                "approved",
                "rejected",
                "action_executed",
                "action_failed",
                "verified",
                "verification_failed",
                "resolved",
                "note_added",
                "error",
                name="event_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_events_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_events")),
        sa.UniqueConstraint("incident_id", "seq", name="incident_id_seq"),
    )
    op.create_index(
        op.f("ix_incident_events_incident_id"), "incident_events", ["incident_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idem_key", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "dead",
                name="job_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "run_after",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("locked_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_jobs_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idem_key", name=op.f("uq_jobs_idem_key")),
    )
    op.create_index(
        "ix_jobs_claimable",
        "jobs",
        ["run_after"],
        unique=False,
        postgresql_where="status = 'pending'",
    )
    op.create_index(op.f("ix_jobs_kind"), "jobs", ["kind"], unique=False)
    op.create_index(
        "ix_jobs_stalled",
        "jobs",
        ["locked_at"],
        unique=False,
        postgresql_where="status = 'running'",
    )
    op.create_table(
        "proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "expired",
                "superseded",
                name="proposal_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_cited", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("similar_incidents", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verification_plan", sa.Text(), nullable=True),
        sa.Column("next_update_minutes", sa.Integer(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decided_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IN ('low','medium','high')", name=op.f("ck_proposals_confidence_valid")
        ),
        sa.CheckConstraint(
            "severity IN ('SEV1','SEV2','SEV3')", name=op.f("ck_proposals_severity_valid")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_proposals_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposals")),
    )
    op.create_index(op.f("ix_proposals_incident_id"), "proposals", ["incident_id"], unique=False)
    op.create_index(op.f("ix_proposals_status"), "proposals", ["status"], unique=False)
    op.create_table(
        "action_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("proposal_id", sa.UUID(), nullable=False),
        sa.Column("action_index", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "skipped",
                name="execution_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("state_before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("state_after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("finished_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_action_executions_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
            name=op.f("fk_action_executions_proposal_id_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_executions")),
        sa.UniqueConstraint("proposal_id", "action_index", name="proposal_id_action_index"),
    )
    op.create_index(
        op.f("ix_action_executions_incident_id"), "action_executions", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_action_executions_proposal_id"), "action_executions", ["proposal_id"], unique=False
    )
    op.create_table(
        "approval_tokens",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("proposal_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("action_index", sa.Integer(), nullable=True),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("consumed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("consumed_by", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('approve','reject')", name=op.f("ck_approval_tokens_decision_valid")
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
            name=op.f("fk_approval_tokens_proposal_id_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_approval_tokens")),
    )
    op.create_index(
        op.f("ix_approval_tokens_proposal_id"), "approval_tokens", ["proposal_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approval_tokens_proposal_id"), table_name="approval_tokens")
    op.drop_table("approval_tokens")
    op.drop_index(op.f("ix_action_executions_proposal_id"), table_name="action_executions")
    op.drop_index(op.f("ix_action_executions_incident_id"), table_name="action_executions")
    op.drop_table("action_executions")
    op.drop_index(op.f("ix_proposals_status"), table_name="proposals")
    op.drop_index(op.f("ix_proposals_incident_id"), table_name="proposals")
    op.drop_table("proposals")
    op.drop_index("ix_jobs_stalled", table_name="jobs", postgresql_where="status = 'running'")
    op.drop_index(op.f("ix_jobs_kind"), table_name="jobs")
    op.drop_index("ix_jobs_claimable", table_name="jobs", postgresql_where="status = 'pending'")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_incident_events_incident_id"), table_name="incident_events")
    op.drop_table("incident_events")
    op.drop_table("slack_deliveries")
    op.drop_index(op.f("ix_kb_chunks_corpus"), table_name="kb_chunks")
    op.drop_index(op.f("ix_kb_chunks_chunk_id"), table_name="kb_chunks")
    op.drop_table("kb_chunks")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index("ix_incidents_slack_thread", table_name="incidents")
    op.drop_index(op.f("ix_incidents_scenario_key"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_key"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_table("control_plane_state")
    # ### end Alembic commands ###
